### ISSUE TITLE
같은 url 주소에 권한 여러개 허용하기

### ISSUE THREAD

**Issue by Chaeyounglim** [Chaeyounglim/myBlog#2]
`        http.authorizeHttpRequests((authorizeHttpRequests) ->
                authorizeHttpRequests
                        .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll() 
                        .requestMatchers("/").permitAll() // 메인 페이지 요청 허가
                        .requestMatchers("/api/user/**").permitAll() 
                        .requestMatchers("/api/posts/**").permitAll() 
                        .requestMatchers("/api/post/**").authenticated() 
                        .anyRequest().authenticated() 
        );`

  .requestMatchers("/api/post/**").authenticated() 코드는 인증된 사용자인 경우 허용하는 코드입니다.
혹시 role이 USER , ADMIN인 사람이 /api/post/** 해당 url에 접근할 수 있도록 한번에 작성할 수 있는 코드는 없을까요?

스프링 부트 2.0 Security에서는 .requestMatchers("/api/post/**).access("hasRole('USER') || hasAuthority('ADMIN')") 이렇게
하면 된다고 나옵니다만, 3.0 버전 이상의 Security에서는 .access() 메서드 내부에 new AuthenticatedAuthorizationManager<>를
넣어주라고 되어 있습니다.

AuthenticatedAuthorizationManager 구현체를 들어가서 보았으나..
해당 생성자 메서드에 파라미터로 AbstractAuthorizationStrategy 타입을 전달받고,
impl를 만들어 보았으나 해결되지 않았습니다.

**Comment by harrycjy1** [comment]
.hasAnyRole("USER", "ADMIN") 을 사용하시면 될거 같아요!

**Comment by Chaeyounglim** [comment]
잘 실행됩니다! 감사합니다!!

커밋 내역
[https://github.com/Chaeyounglim/myBlog/commit/6129e513bd783846036c9e0902091e024170dc7e](url)
